# Generated by Django 5.0.4 on 2024-04-16 07:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OffChainData',
            fields=[
                ('offchain_timestamp', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0)),
                ('lastupdated', models.DateField(default=datetime.date(2024, 4, 16))),
            ],
        ),
        migrations.CreateModel(
            name='OnChainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.FloatField(default=0)),
                ('high', models.FloatField(default=0)),
                ('low', models.FloatField(default=0)),
                ('close', models.FloatField(default=0)),
                ('volume', models.FloatField(default=0)),
                ('block', models.IntegerField(default=0)),
                ('lastupdated', models.DateField(default=datetime.date(2024, 4, 16))),
                ('onchain_timestamp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appfetch.offchaindata')),
            ],
        ),
    ]
