# Generated by Django 5.0.4 on 2024-04-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfetch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offchaindata',
            name='lastupdated',
        ),
        migrations.RemoveField(
            model_name='onchaindata',
            name='lastupdated',
        ),
    ]
