# Generated by Django 5.0.4 on 2024-04-16 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfetch', '0002_remove_offchaindata_lastupdated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onchaindata',
            name='close',
        ),
        migrations.RemoveField(
            model_name='onchaindata',
            name='high',
        ),
        migrations.RemoveField(
            model_name='onchaindata',
            name='low',
        ),
        migrations.RemoveField(
            model_name='onchaindata',
            name='volume',
        ),
    ]
