# Generated by Django 5.0.4 on 2024-04-16 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfetch', '0004_rename_offchain_timestamp_offchaindata_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offchaindata',
            name='last_updated',
            field=models.DateField(default=datetime.date(2024, 4, 16)),
        ),
    ]
