# Generated by Django 5.0.4 on 2024-04-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfetch', '0006_onchaindata_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offchaindata',
            old_name='price',
            new_name='priceCoingecko',
        ),
        migrations.RenameField(
            model_name='onchaindata',
            old_name='block',
            new_name='blockNo',
        ),
        migrations.RenameField(
            model_name='onchaindata',
            old_name='price',
            new_name='priceUniswapV3',
        ),
    ]
